apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: application-menu-rh-developer-blog
spec:
  href: https://www.arrow.com/globalecs/de/produkte/
  location: ApplicationMenu
  text: Arrow Landingpage
  applicationMenu:
    section: Kubernetes Blogs
    imageURL: https://i.ibb.co/pZ0Lxdb/Logo-Red-Hat-Hat-Color-RGB.png
