apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: application-menu-rh-developer-blog
spec:
  href: https://www.arrow.com/globalecs/de/produkte/
  location: ApplicationMenu
  text:  Arrow Portfolio
  applicationMenu:
    section: Arrow AI Lab
    imageURL: https://upload.wikimedia.org/wikipedia/commons/0/04/Arrow_Electronics_logo.svg
